### ISSUE TITLE
添加删除线在 iOS 10.3 系统下不显示

### ISSUE THREAD

**Issue by lifeMiik** [joeshang/SCRAttributedStringBuilder#2]
在 iOS11 下为正常，估计是个系统 bug。

**Comment by joeshang** [comment]
删除线是系统问题，具体见 https://stackoverflow.com/questions/43074652/ios-10-3-nsstrikethroughstyleattributename-is-not-rendered-if-applied-to-a-sub， 我对 SCRAttributedStringBuilder 的定位只是对系统方法做封装，使得调用起来比较方便，并不处理这个问题。可以通过拼上 baseline 来处理这个问题。
