### ISSUE TITLE
Cannot add image at the beginning of the String

### ISSUE THREAD

**Issue by zjyharry** [joeshang/SCRAttributedStringBuilder#3]
In AttributedStringBuilder.swift line 66, out of index error

**Comment by joeshang** [comment]
谢谢提出问题，我处理一下。

在开头增加图片的话，建议用 appendImage(_ image: UIImage, _ font: UIFont) 方法，因为为了居中效果，最好指定一个 font 进行处理。

**Comment by joeshang** [comment]
发布了 [1.1.3](https://github.com/joeshang/SCRAttributedStringBuilder/releases/tag/1.1.3)，修复了该问题
